# Generated by Django 4.0.2 on 2022-07-01 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items_json',
            new_name='itemjson',
        ),
    ]
