# Generated by Django 4.0.2 on 2022-07-01 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0004_rename_items_json_order_itemjson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='itemjson',
            new_name='itemJson',
        ),
    ]
